management:
  endpoints:
    enabled-by-default: true
    health:
      show-details: always
      show-components: always
    web:
      exposure:
        include: '*'

spring:
  messages:
    basename: "messages,config.i18n.messages"
    fallback-to-system-locale: true        
