eureka:
  instance:
    preferIpAddress: true

---
spring:
  config:
    activate:
      on.profile: peer1
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8080/eureka/,http://peer3:8080/eureka/

---
spring:
  config:
    activate:
      on.profile: peer2
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8080/eureka/,http://peer3:8080/eureka/

---
spring:
  config:
    activate:
      on.profile: peer3
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8080/eureka/,http://peer2:8080/eureka/