eureka:
  client:
    serviceUrl:
      defaultZone: https://peer1/eureka/,http://peer2/eureka/,http://peer3/eureka/

---
spring:
  config:
    active:
      on-profile: peer1
eureka:
  instance:
    hostname: peer1

---
spring:
  config:
    active:
      on-profile: peer2
eureka:
  instance:
    hostname: peer2

---
spring:
  config:
    active:
      on-profile: peer3
eureka:
  instance:
    hostname: peer3
